"""add_cancellation_fee_to_payments

Revision ID: 6b48b2a09840
Revises: cda48ecc5c57
Create Date: 2026-07-14 16:38:12.417989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b48b2a09840'
down_revision: Union[str, Sequence[str], None] = 'cda48ecc5c57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('cancellation_fee', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'cancellation_fee')
    # ### end Alembic commands ###
